### PR TITLE
Adds support for IPv6

### PR DESCRIPTION
**Pull request by eelcocramer**
This is a follow up for #9 which I pushed to soon 👎 

This time it should be fine.

* Adds support for IPv6
* Adds test cases for IPv6
* Removes a duplicate check for origin less broadcast
* Adds a configuration property to set the listen IP address
* The application is now responsible for passing a correct listen IP address to smudge.
* Adds documentation on how to test Smudge with IPv4 and IPv6 using Docker.

This should of course fix issue #7

### CODE REVIEW

**Comment by clockworksoul** [comment]
I'll try to take a look asap. I'm neck-deep in documentation for work, but I want to get to this today if I can.

What time zone are you in, @eelcocramer ?

**Comment by clockworksoul** [comment]
> What time zone are you in, @eelcocramer ?

Nevermind! Found it: GMT+1
I'll try to have this reviewed before it gets too late, your time.

**Comment by eelcocramer** [comment]
No hurries. I am located in Amsterdam, The Netherlands. So CET.

**Comment by eelcocramer** [comment]
Broadcasts on IPv4 are currently not working correctly with my code. When receiving a broadcast Smudge now logs:

```
 Warn 17/Jan/2018:16:05:29 UTC - Received originless broadcast
```

On IPv6 broadcasts are working fine. I will investigate and add the fix to this PR.

**Comment by eelcocramer** [comment]
The last commit fixes receiving broadcasts on IPv4.

**Comment by eelcocramer** [comment]
To discuss: what would be a sensible value to suggest to use for MaxBroadcastBytes on IPv6. Currently I set this to 1280 bytes but this is of course not sensible as there should be room reserved for the headers and members. How does 512 sounds (extrapolating the room reserved in IPv4)?

**Comment by clockworksoul** [comment]
Apologies for the delay! I've been suffering from the flu for the past few days. I'm starting to feel human though. I'll take a look ASAP.

**Comment by eelcocramer** [comment]
No problem. I needed the time to tie some loose ends anyway.

**Comment by eelcocramer** [comment]
Today I tested this code on a simulated [openthread network](https://codelabs.developers.google.com/codelabs/openthread-simulation/) and everything seems to work fine.

**Review by clockworksoul — APPROVED** [review]
Everything looks great!

Approved 👍

**Comment by eelcocramer** [comment]
Thanks!

**Pull request merged**
