### PR TITLE
Adds support for IPv6

### PR DESCRIPTION
**Pull request by eelcocramer**
First of all, thanks a lot for creating this library. I wanted to test this on a 6lowpan so I've put some effort into adding IPv6 support.

I've made the following changes:

* Adds support for IPv6
* Adds test cases for IPv6
* Removed a duplicate check for origin less broadcast
* Added a configuration property to set the listen IP address
* The application is now responsible for passing a correct listen IP address to smudge.

This should of course fix issue #7 

I would really appreciate your feedback!

### CODE REVIEW

**Comment by eelcocramer** [comment]
I'm not convinced everything works fine yet. I will create a new PR if it is.

**Comment by clockworksoul** [comment]
@eelcocramer No worries! I appreciate the contribution! 

If you want, you can reopen, and we can jointly test and debug.

**Comment by clockworksoul** [comment]
The only thing I would ask is if you have multiple independent changes that you create a new PR for each (IPv6 support + tests, setting the listen IP address). It makes them easier to review and merge. :)

Thanks again!

**Comment by eelcocramer** [comment]
I've just completed the implementation, I will create a new PR.

As for the independent changes: I see you point. But all changes were needed to create the IPv6 support. I've flattened my original commits as I worked quite iterative and did want to mess up your commit history. My working branch is still in my fork (`ipv6` branch) but that branch does not hold my final commit.

**Comment by clockworksoul** [comment]
That's fine. Fortunately there aren't a hundred files changed, so I'll manage :)

**Pull request closed without merging**
